=== Prismatik/auth/schemas/entity.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "entity - entities",
  "description": "An entity",
  "type": "object",
  "additionalProperties": false,
  "definitions": {
    "id": {
      "description": "unique identifier of entity",
      "example": "62bb01a7-7af2-467b-935d-fed7953d3a17",
      "format": "uuid",
      "type": "string"
    },
     "rev": {
      "description": "unique identifier of a revision",
      "example": "62bb01a7-7af2-467b-935d-fed7953d3a17",
      "format": "uuid",
      "type": "string"
    },
    "created_at": {
      "description": "when entity was created",
      "example": "2012-01-01T12:00:00Z",
      "format": "date-time",
      "type": "string"
    },
    "updated_at": {
      "description": "when entity was updated",
      "example": "2012-01-01T12:00:00Z",
      "format": "date-time",
      "type": "string"
    },
    "emails": {
      "type": "array",
      "items": {
        "example": "bob@example.com",
        "type": "string",
        "format": "email"
      }
    },
    "name": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "full": {
          "type": "string",
          "example": "Doris McCafferty"
        },
        "short": {
          "type": "string",
          "example": "Doris"
        }
      }
    },
    "password": {
      "description": "entity's password",
      "example": "s3cr3t",
      "type": "string"
    },
    "permissions": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/permission"
      }
    },
    "permission": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "example": "membership"
        },
        "entity": {
          "type": "string",
          "example": "62bb01a7-7af2-467b-935d-fed7953d3a17"
        }
      }
    }
  },
  "links": [
    {
      "description": "create a new entity",
      "href": "/entities",
      "method": "POST",
      "rel": "create",
      "schema": {
        "properties": {
          "emails": {
            "$ref": "#/definitions/emails"
          },
          "name": {
            "$ref": "#/definitions/name"
          },
          "password": {
            "$ref": "#/definitions/password"
          },
          "permissions": {
            "$ref": "#/definitions/permissions"
          }
        },
        "type": [
          "object"
        ]
      },
      "title": "Create"
    },
    {
      "description": "get info for existing entity",
      "href": "/entities/{(%23%2Fdefinitions%2Fid)}",
      "method": "GET",
      "rel": "self",
      "title": "Info"
    },
    {
      "description": "update entire existing entity",
      "href": "/entities/{(%23%2Fdefinitions%2Fid)}",
      "method": "PUT",
      "rel": "update",
      "schema": {
        "properties": {
          "emails": {
            "$ref": "#/definitions/emails"
          },
          "name": {
            "$ref": "#/definitions/name"
          },
          "password": {
            "$ref": "#/definitions/password"
          },
          "permissions": {
            "$ref": "#/definitions/permissions"
          }
        },
        "required": [
          "rev",
          "emails",
          "name",
          "permissions"
        ],
        "type": [
          "object"
        ]
      },
      "title": "Update entire entity"
    },
    {
      "description": "update partial existing entity",
      "href": "/entities/{(%23%2Fdefinitions%2Fid)}",
      "method": "PATCH",
      "rel": "update",
      "schema": {
        "properties": {
          "emails": {
            "$ref": "#/definitions/emails"
          },
          "name": {
            "$ref": "#/definitions/name"
          },
          "password": {
            "$ref": "#/definitions/password"
          },
          "permissions": {
            "$ref": "#/definitions/permissions"
          }
        },
        "required": [
          "rev"
        ],
        "type": [
          "object"
        ]
      },
      "title": "Update partial entity"
    },
    {
      "description": "remove an existing entity",
      "href": "/entities/{(%23%2Fdefinitions%2Fid)}",
      "method": "DELETE",
      "rel": "delete",
      "title": "Delete"
    }
  ],
  "id": "/entity",
  "properties": {
    "id": {
      "$ref": "#/definitions/id"
    },
    "rev": {
      "$ref": "#/definitions/rev"
    },
    "created_at": {
      "$ref": "#/definitions/created_at"
    },
    "updated_at": {
      "$ref": "#/definitions/updated_at"
    },
    "emails": {
      "$ref": "#/definitions/emails"
    },
    "name": {
      "$ref": "#/definitions/name"
    },
    "password": {
      "$ref": "#/definitions/password"
    },
    "permissions": {
      "$ref": "#/definitions/permissions"
    },
    "inherited_permissions": {
      "$ref": "#/definitions/permissions"
    }
  }
}

=== Prismatik/auth/test/fixtures/entities.json
[{
  "id": "015f04df-af79-450c-9c10-08bafc9a1da3",
  "rev": "5f8f51e1-732d-418f-98a8-c9380524da50",
  "created_at": "2012-01-01T12:00:00Z",
  "updated_at": "2012-01-01T12:00:00Z",
  "emails": ["alice@inchains.com.au"],
  "name": {
    "full": "Alice",
    "short": "Al"
  },
  "password": "eVmXazS3jsJ3CozuyXB8WInflmjfGd",
  "permissions": [],
  "inherited_permissions": []
},
{
  "id": "62bb01a7-7af2-467b-935d-fed7953d3a17",
  "rev": "5f8f51e1-732d-418f-98a8-c9380524da50",
  "created_at": "2012-01-01T12:00:00Z",
  "updated_at": "2012-01-01T12:00:00Z",
  "emails": ["bob@bobatron.com.au"],
  "name": {
    "full": "Bob",
    "short": "Bob"
  },
  "password": "eVmXazS3jsJ3CozuyXB8WInflmjfGd",
  "permissions": [],
  "inherited_permissions": []
},
{
  "id": "2a8c6e26-a75e-4f0a-907f-711f04833851",
  "rev": "5f8f51e1-732d-418f-98a8-c9380524da50",
  "created_at": "2012-01-01T12:00:00Z",
  "updated_at": "2012-01-01T12:00:00Z",
  "emails": ["garry@topdollarcurtains.com.au"],
  "name": {
    "full": "Garry",
    "short": "Gaz"
  },
  "password": "eVmXazS3jsJ3CozuyXB8WInflmjfGd",
  "permissions": [{
    "type": "owner",
    "entity": "015f04df-af79-450c-9c10-08bafc9a1da3"
  }],
  "inherited_permissions": []
},
{
  "id": "7aeaafb2-d194-449c-8fa7-2cc54873ffea",
  "rev": "5f8f51e1-732d-418f-98a8-c9380524da50",
  "created_at": "2012-01-01T12:00:00Z",
  "updated_at": "2012-01-01T12:00:00Z",
  "emails": ["managers@thatplace.com.au"],
  "name": {
    "full": "Managers",
    "short": "Man?"
  },
  "password": "",
  "permissions": [{
    "type": "member",
    "entity": "62bb01a7-7af2-467b-935d-fed7953d3a17"
  },
  {
    "type": "owner",
    "entity": "2a8c6e26-a75e-4f0a-907f-711f04833851"
  }],
  "inherited_permissions": []
}]
